title: RTKA Documentation
description: Recursive Ternary Knowledge Algorithm
theme: minima  # Or another Jekyll theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
